### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver.Steam.Deploy#2]
- [ ] Implement printing just hashes after build
- [ ] Automate submitting new builds to API
- [ ] Add option to use different config files (path for game) when building
- [ ] Implement steamcmd into deploy
